  CREATE TABLE IF NOT EXISTS ajay_table (
        id SERIAL PRIMARY KEY,
        emp_name VARCHAR(255) NOT NULL,
        emp_email VARCHAR(255) UNIQUE NOT NULL,
        emp_gender VARCHAR(20),
        emp_marital_status VARCHAR(20),
        emp_dob DATE,
        emp_mobile VARCHAR(20),
        emp_alt_mobile VARCHAR(20),
        emp_aadhaar VARCHAR(20) UNIQUE,
        emp_pan VARCHAR(20) UNIQUE,
        emp_address TEXT,
        emp_city VARCHAR(100),
        emp_state VARCHAR(100),
        emp_zipcode VARCHAR(20),
        emp_bank VARCHAR(255),
        emp_account VARCHAR(50),
        emp_ifsc VARCHAR(20),
        emp_bank_branch VARCHAR(100),
        emp_job_role VARCHAR(255),
        emp_department VARCHAR(255),
        emp_experience_status VARCHAR(20),
        emp_joining_date DATE,
        emp_profile_pic VARCHAR(255),
        emp_ssc_doc VARCHAR(255),
        ssc_school VARCHAR(255),
        ssc_year INTEGER,
        ssc_grade VARCHAR(20),
        emp_inter_doc VARCHAR(255),
        inter_college VARCHAR(255),
        inter_year INTEGER,
        inter_grade VARCHAR(20),
        inter_branch VARCHAR(100),
        emp_grad_doc VARCHAR(255),
        grad_college VARCHAR(255),
        grad_year INTEGER,
        grad_grade VARCHAR(20),
        grad_degree VARCHAR(100),
        grad_branch VARCHAR(100),
        resume VARCHAR(255),
        id_proof VARCHAR(255),
        signed_document VARCHAR(255),
        emp_terms_accepted BOOLEAN DEFAULT FALSE,
        primary_contact_name VARCHAR(255),
        primary_contact_mobile VARCHAR(20),
        primary_contact_relation VARCHAR(50),
        primary_contact_email VARCHAR(255),
        secondary_contact_name VARCHAR(255),
        secondary_contact_mobile VARCHAR(20),
        secondary_contact_relation VARCHAR(50),
        secondary_contact_email VARCHAR(255),
        previous_employments JSONB,
        additional_educations JSONB,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )